// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dplrmwinaeziqkpgpyqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwbHJtd2luYWV6aXFrcGdweXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjA2NjQsImV4cCI6MjA2MjE5NjY2NH0.ClkDGzuIVwKQudSR7DOv1CyzrtnHGQ1JMR-c6dKaRw8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);